version: '3'
networks:
  mynetwork:
services:
  db:
    container_name: postgres-rest
    build:
      context: .
      dockerfile: Dockefile-db
    restart: always
    ports:
      - '5432:5432'
    environment:
    - POSTGRES_USER=restaurant_manager
    - POSTGRES_PASSWORD=b24de59f8c8fe841be3b
    - POSTGRES_DB=restaurant_api
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U restaurant_manager -d restaurant_api"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONPATH=/app
      - POSTGRES_HOST=postgres-rest
      - POSTGRES_USER=restaurant_manager
      - POSTGRES_PASSWORD=b24de59f8c8fe841be3b
      - POSTGRES_DB=restaurant_api
    networks:
      - mynetwork
