FROM postgres:15.1-alpine

ENV POSTGRES_USER restaurant_manager-test
ENV POSTGRES_PASSWORD b24de59f8c8fe841be3b
ENV POSTGRES_DB restaurant_api-test
ENV POSTGRES_HOST postgres-rest

COPY /create.sql /docker-entrypoint-initdb.d/