version: '3'
networks:
  test-network:
services:
  db:
    container_name: postgres-rest-test
    build:
      context: .
      dockerfile: Dockerfile-db-test
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - test.env
    networks:
      - test-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U restaurant_manager-test -d restaurant_api-test" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - test.env
    networks:
      - test-network

  tests:
    build:
      context: .
      dockerfile: Dockerfile-test
    networks:
      - test-network
    command: >
      bash -c "python create_tables.py
      && pytest app/tests/menu_test.py app/tests/submenu_test.py app/tests/dish_test.py"
    depends_on:
      db:
        condition: service_healthy
      app:
        condition: service_started
    env_file:
      - test.env

  redis:
    container_name: redis-test
    image: redis
    ports:
      - "6379:6379"
    networks:
      - test-network
