version: '3'
networks:
  PlayNetwork:
services:
  db:
    container_name: postgres-rest
    build:
      context: .
      dockerfile: Dockefile-db
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    networks:
      - PlayNetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U restaurant_manager -d restaurant_api"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - PlayNetwork

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - PlayNetwork
    command: pytest tests/menu_test.py tests/submenu_test.py tests/dish_test.py
    depends_on:
      db:
        condition: service_healthy
      app:
        condition: service_started