version: '3'
networks:
  mynetwork:
services:
  db:
    container_name: postgres-rest
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U restaurant_manager -d restaurant_api" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    networks:
      - mynetwork

  redis:
    container_name: redis-cache
    image: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork
