version: '3'
networks:
  mynetwork:
services:
  db:
    image: postgres:15.1-alpine
    ports:
      - '5432:5432'
    expose:
      - 5432
    env_file:
      - .env
    networks:
      - mynetwork
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - mynetwork